title: Data 198
description: Introduction to Real World Data Science
logo: assets/site_images/dsslogo.png
author: Directors of Academic Development Fall 24
email: dss.data198@gmail.com
theme: just-the-docs
current_week: 11
favicon: assets/site_images/favicon.ico
#url: "https://dssdecal.org"
baseurl: "/fa24"

url: https://dssdecal.github.io # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

html:
  favicon                   : "assets/site_images/dss.png"  # A path to a favicon image

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.3.3
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Textbook: 
    - https://dssdecal.org/textbook
  Syllabus: 
    - 'https://docs.google.com/document/d/1Dz6GFDBfU3S_VzzhqRJwBhNhM4sqR1jQ02erfx0rhFQ/edit?usp=sharing'
  Data Science Society at Berkeley:
    - 'https://dssberkeley.com'
  bCourses: 
    - 'https://bcourses.berkeley.edu/courses/1539886'

links: 
  lectures: 
    lecture01: "https://docs.google.com/presentation/d/1Y6ezn8ce3wFs6vQvDmse9NEn62bD7Fdj0wxOlEjnckc/edit?usp=sharing"
    lecture02: "https://docs.google.com/presentation/d/1W1BiLirR5FE6RXjE4Y-ifCanVRpg9oaZjTbIdbVdUjw/edit?usp=sharing"
    lecture03: "https://docs.google.com/presentation/d/17wKBi6-kg8QnWb2ecXX7o3Pqs94Qnjw-emxIC4RwDec/edit?usp=sharing"
    lecture04: "https://docs.google.com/presentation/d/1x2JPtYYrJRha4F_jYQJeWWhwohKNidZMiFKQo5nqi9w/edit?usp=sharing"
    lecture05: "https://docs.google.com/presentation/d/1cT2F-u0tukJWCUcAZiGri2qhG3bT4SYJEItaWMSPYe4/edit?usp=sharing"
    lecture06: "https://docs.google.com/presentation/d/1h4J_JaqVuz8H3fLKTsv_FHxMaS_NDcFMppCBK0KLPfc/edit?usp=sharing"
    lecture07: "https://docs.google.com/presentation/d/11zfNBLpJGpo4WkooCv6TyuahyhpWjVXR4ssGNtYkeuw/edit?usp=sharing"
  demos: 
    demo01: "https://deepnote.com/workspace/joseph-zhai-4d2cff32-3181-4ae6-a47d-dc9f02262638/project/DSS-Acadev-Lecture-2-Duplicate-82001e9c-93b5-41ef-a966-40cb86c2e838/notebook/Notebook%201-f92f2b9db8e749958ae2ed633fcaf634"
    demo02: "https://hub.ovh2.mybinder.org/user/dss-data198-demos-n98zi3r7/doc/tree/data_cleaning/Notebook.ipynb"
    demo03: "https://www.google.com/url?q=https://shorturl.at/TExkv&sa=D&source=editors&ust=1729556860915882&usg=AOvVaw0nQGz8XC_vWOcHn2DgWCIB"
    demo04: "https://deepnote.com/workspace/jakex-26b2579d-a0a9-4866-9a6e-9a76f523e999/project/Jake-Xiangs-Untitled-project-82de45cb-e433-41e9-b20c-61411c9da3ba/notebook/DSS-FA24-Hypothesis-Testing-44e9d2213a5c4a54a8910d88904f60b4"
    demo05: "https://deepnote.com/workspace/ryans-workspace-1ba5-0c12a51c-2c5f-47ce-a403-8e829787a597/project/Basic-Machine-Learning-Models-0eb92a08-1222-4b3c-81be-312c63bd701b/notebook/dss-ml-9dede94526244b75a0dd8710525491b0"
    demo06: "https://deepnote.com/workspace/ryans-workspace-1ba5-0c12a51c-2c5f-47ce-a403-8e829787a597/project/Basic-Machine-Learning-Models-0eb92a08-1222-4b3c-81be-312c63bd701b/notebook/dss-ml-9dede94526244b75a0dd8710525491b0"
  readings: 
    reading01: "https://ds100.org/course-notes/pandas_1/pandas_1.html"
    reading02: "https://ds100.org/course-notes/pandas_2/pandas_2.html"
    reading03: "https://ds100.org/course-notes/pandas_3/pandas_3.html"
    reading04: "https://deepnote.com/app/rickyharyanto14-3390/Data-Cleansing-Study-Case-Telco-a8a54d4a-e82e-49f3-ab82-14ee2121c94b"
  lightning: 
    talk01: "https://docs.google.com/presentation/d/1mcyHE5bQJY2eRIo28vxuH9JREduxVmcvHIGUEcrt7Pk/edit?usp=sharing"
    talk02: "https://docs.google.com/presentation/d/1kiG963T-ybbWlfVqGvltJj1060Kq8ukonW0emick0Ro/edit?usp=sharing"

  

# Collections for website data
collections: 
  acknowledgers:
  staffers:
  modules:
  schedules:
  announcements:


defaults: #Used to define the default settings for different collections or types of content
  - scope: #Determines where the default settings should apply.
      path: "" #The path where the default settings should apply to, if "" means it will apply globally to the specific type across the site
      type: staffers #The specific collection
    values: 
      layout: staffer #which specific layout to use
      subpath: "/assets/images/" #what's the default subpath for this file
  - scope:
      path: ""
      type: modules
    values:
      layout: module
  - scope:
      path: ""
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ""
      type: announcements
    values:
      layout: announcement
  - scope:
      path: ""
      type: acknowledgers
    values:
      layout: acknowledger
      subpath: "/assets/images/"


#After site is built, but before it is published!
compress_html: #compresses HTML output, making the HTML files smaller, thus increasing performance of the website
  clippings: all #all unnecessary parts or "cippings" of HTML are removed (redundant tags and the like)
  comments: all #removes all comments
  endings: all #remove optional closing tags (tags which don't need closing to still work)
  startings: [] #no specific action to compress the beginning of HTML elements
  blanklines: false #blank lines not removed, as they are valuable in reading code easily
  profile: false #doesn't generate a profiling report

plugins:
  - jekyll-seo-tag

markdown: kramdown #specifies to use kramdown, a Ruby gem that parses markdowns and converts it to HTML
kramdown:
  input: GFM #Input is GitHub Flavored Markdown, so the same one that GitHub uses
  hard_wrap: false #Single newlines in the Markdown will not translate into <br> tagsl, so empty lines just signify new <p>
  enable_coderay: false #Doesn't enable CodeRay, a Ruby Gem syntax highlighter
safe: false #Allows for the use of custom plugins and non-whitelisted Ruby gems in your Jekyll project